name: Prisma Cloud Compute Image Scan

on: [push, pull_request]

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}

services:
  docker:
    image: docker:19.03-dind
    options: --privileged

jobs:
  # Jobs are ran independently from each other, so build and scan needs to be in a single job.
  build-and-scan:
    name: Build and scan image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download twistcli from the Prisma Cloud Compute Console
        run: |
          curl --insecure --user ${{ secrets.PCC_USER }}:${{ secrets.PCC_PASS }} --output ./twistcli ${{ secrets.PCC_CONSOLE_URL }}/api/v1/util/twistcli
          chmod a+x ./twistcli

      - name: Build the image
        run: |
          cat <<EOF | tee ${{ github.workspace }}/Dockerfile
          FROM nginx:1.21
          EXPOSE 80
          CMD ["nginx", "-g", "daemon off;"]
          EOF
          docker build -t $IMAGE_NAME .

      - name: Scan the image
        run: ./twistcli images scan --docker-address http://docker:2375 --address $PCC_CONSOLE_URL --user $PCC_USER --password $PCC_PASS --details $IMAGE_NAME
